---
- name: Testing andrewrothstein.loft
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'loft --version'
      ansible.builtin.command: loft --version
      changed_when: false
      register: loft_test_output
    - name: Output from 'loft --version'
      ansible.builtin.debug:
        msg: '{{ loft_test_output.stdout }}'
