---
- hosts: all
  roles:
  - role: '{{ playbook_dir }}'
  tasks:
  - command: /usr/local/bin/loft --version
    register: loft_test_output
  - debug:
      msg: '{{ loft_test_output.stdout }}'
  - command: /usr/local/bin/loft-devspace-plugin --version
    register: loft_dsp_test_output
  - debug:
      msg: '{{ loft_dsp_test_output.stdout }}'
